#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tandoor"
name = "Tandoor"
description.en = "Manage and share recipes, plan meals, build shopping lists"
description.fr = "Gérez et partagez des recettes, planifiez des repas, créez des listes de courses"

version = "2.6.13~ynh9"

maintainers = ["Navan Chauhan"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://tandoor.dev"
demo = "https://app.tandoor.dev/accounts/login/?demo"
admindoc = "https://docs.tandoor.dev"
userdoc = "https://docs.tandoor.dev"
code = "https://github.com/TandoorRecipes/recipes"
cpe = "cpe:2.3:a:tandoor:recipes"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = [ "armhf", "arm64", "amd64" ]
multi_instance = true

ldap = true
sso = true

disk = "1000M"
ram.build = "2000M"
ram.runtime = "1500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/TandoorRecipes/recipes/archive/refs/tags/2.6.13.tar.gz"
    sha256 = "b2c8166568dd37228793176459c91c9a9ac0f7b88c927bc127a2728a80281c2d"
    in_subdir = true

    autoupdate.strategy = "latest_github_tag"

    [resources.sources.uv]
    amd64.url = "https://github.com/astral-sh/uv/releases/download/0.12.8/uv-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "2e2b37e9811e17675a9e70bed5e1a58fc8c0388be63d751d72cc735188c149ff"
    arm64.url = "https://github.com/astral-sh/uv/releases/download/0.12.8/uv-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "ba8661f4fd207c8e94814191598e619b355ac10d5014e851e21eb800f9ef2b00"
    armhf.url = "https://github.com/astral-sh/uv/releases/download/0.12.8/uv-armv7-unknown-linux-gnueabihf.tar.gz"
    armhf.sha256 = "bc80826f631f8836a974a88b8cf797935bc83f15552828ad5de0195f6246e333"

    in_subdir = true

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/astral-sh/uv"
    autoupdate.asset.amd64 = "^uv-x86_64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.arm64 = "^uv-aarch64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.armhf = "^uv-armv7-unknown-linux-gnueabihf.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    subdirs = ["media"]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    media.url = "/media"
    media.allowed = "visitors"
    media.show_tile = false
    media.protected = true

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "git",
        "curl",
        "libpq-dev",
        "postgresql",
        "libsasl2-dev",
        "python3-dev",
        "libldap2-dev",
        "libssl-dev",
        "libffi-dev",
        "autoconf",
        "build-essential",
        "libxmlsec1-dev",
        "pkg-config",
        "redis-server",
    ]

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
