#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

timezone="$(timedatectl show --value --property=Timezone)"
version=$(ynh_app_upstream_version)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Updating NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env mediafiles"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="dot_env" --destination="$install_dir/.env"

ynh_config_add --template="version.py" --destination="$install_dir/recipes/version.py"

#=================================================
# SPECIFIC SETUP
#=================================================
ynh_script_progression "Installing $app..."

_tandoor_build_frontend

_tandoor_venv_install

pushd "$install_dir"
    (
        source "$install_dir/.env"
        ynh_hide_warnings ynh_exec_as_app "$venvpy" manage.py migrate
        ynh_psql_db_shell <<< "ALTER USER $app WITH NOSUPERUSER;"
        ynh_hide_warnings ynh_exec_as_app "$venvpy" manage.py collectstatic --no-input
    )
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Smart recipe management" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
